import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/Layouts/mainLayout";
import { TamstackQueryProvider } from "@/components/providers/tanstack-query.provider";
import ProgressBar from "@/components/ui/progress-bar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scrollbar-thin scrollbar-thumb-primary scrollbar-track-background">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <TamstackQueryProvider>
                    <MainLayout>{children}</MainLayout>
                </TamstackQueryProvider>
                <ProgressBar/>
            </body>
        </html>
    );
}
