/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIdRouteImport } from './routes/tv/$id'
import { Route as MoviesIdRouteImport } from './routes/movies/$id'
import { Route as tabsSettingsIndexRouteImport } from './routes/(tabs)/settings/index'
import { Route as tabsSearchIndexRouteImport } from './routes/(tabs)/search/index'
import { Route as tabsHomeIndexRouteImport } from './routes/(tabs)/home/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsSettingsIndexRoute = tabsSettingsIndexRouteImport.update({
  id: '/(tabs)/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsSearchIndexRoute = tabsSearchIndexRouteImport.update({
  id: '/(tabs)/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsHomeIndexRoute = tabsHomeIndexRouteImport.update({
  id: '/(tabs)/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/movies/$id': typeof MoviesIdRoute
  '/tv/$id': typeof TvIdRoute
  '/home': typeof tabsHomeIndexRoute
  '/search': typeof tabsSearchIndexRoute
  '/settings': typeof tabsSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/movies/$id': typeof MoviesIdRoute
  '/tv/$id': typeof TvIdRoute
  '/home': typeof tabsHomeIndexRoute
  '/search': typeof tabsSearchIndexRoute
  '/settings': typeof tabsSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/movies/$id': typeof MoviesIdRoute
  '/tv/$id': typeof TvIdRoute
  '/(tabs)/home/': typeof tabsHomeIndexRoute
  '/(tabs)/search/': typeof tabsSearchIndexRoute
  '/(tabs)/settings/': typeof tabsSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/movies/$id'
    | '/tv/$id'
    | '/home'
    | '/search'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/movies/$id'
    | '/tv/$id'
    | '/home'
    | '/search'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/movies/$id'
    | '/tv/$id'
    | '/(tabs)/home/'
    | '/(tabs)/search/'
    | '/(tabs)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  MoviesIdRoute: typeof MoviesIdRoute
  TvIdRoute: typeof TvIdRoute
  tabsHomeIndexRoute: typeof tabsHomeIndexRoute
  tabsSearchIndexRoute: typeof tabsSearchIndexRoute
  tabsSettingsIndexRoute: typeof tabsSettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/settings/': {
      id: '/(tabs)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof tabsSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/search/': {
      id: '/(tabs)/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof tabsSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/home/': {
      id: '/(tabs)/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof tabsHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  MoviesIdRoute: MoviesIdRoute,
  TvIdRoute: TvIdRoute,
  tabsHomeIndexRoute: tabsHomeIndexRoute,
  tabsSearchIndexRoute: tabsSearchIndexRoute,
  tabsSettingsIndexRoute: tabsSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
